PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
  ?s schema:name ?label .
  ?s schema:description ?comment .
}
WHERE {
  { ?s rdfs:label ?label . }
  UNION
  { ?s rdfs:comment ?comment . }
}
